### technical validation of Co-Phasing
# we generate 10 co-phased allele-specific chromatin contact maps from a subsampled F123 genome
# we compare those to the allele-specific chromatin contact maps generated by reads overlapping all known F123 SNPs (no co-phasing, no subsampling)
# UPDATE 18.05.21 : subsample again with 1SNP every 2kb (see below)
################################################################################
### steps here in R:
# subsample F123 to human SNP density (10 times)
# for each subsampled genome, generate seed SNPs files for each GAM sample
################################################################################
################################################################################
##### subsampling F123 #########################################################
################################################################################
################################################################################
# F123 SNPs are filtered for mininum mappability of 1, 
# load truth
full_SNPs_mm10 = readRDS('/fast/groups/ag_schwarz/Projects/project-gam/prelim/clean_mm10_gt_merged_mappability_minmap1.rds')
nrow(full_SNPs_mm10)
# 18150228

# check SNP density here again:
# split into chromosomes, calc distance
SNPs_mm10_chr = split(full_SNPs_mm10, full_SNPs_mm10$CHROM)
mm10_SNP_dist=unlist(lapply(SNPs_mm10_chr,function(chr){
    dist=diff(chr$POS)
}))
mean(mm10_SNP_dist) # 132.3968
median(mm10_SNP_dist) # 56

# check distribution of SNPs on CAST and J129 alleles:
table(full_SNPs_mm10$F123_GT)/nrow(full_SNPs_mm10)
#       0|1       1|0
# 0.1288906 0.8711094

# check again the SNP density by just seeing how many SNPs we have for how many basepairs in the genome:
# mouse genome is how long?
chromsize_mm10=read.table('/fast/groups/ag_schwarz/Projects/project-gam/RNAseq/data/Rieke_current/genome/chromsize.tsv',header = T)
sum(chromsize_mm10$size)/nrow(full_SNPs_mm10)
# 135.6867
# almost the same as the calculated distance above

# now we want to lower the SNP density to ~ 1 SNP every 1000bp (1kb), means we need x number of SNPs for the mouse genome length
nr_subsampled_SNPs = sum(chromsize_mm10$size)/1000 #[1] 2462745
nr_subsampled_SNPs/nrow(full_SNPs_mm10)*100 # 13.56867 % 

# I will sample indizes of the rows, so I can easily subset the SNP df
subsampled_F123_list = vector(mode = "list", length = 10)
for(seed in 1:10){
    set.seed(seed)
    SNPs_mm10_subsampled_indizes = sample(x = nrow(full_SNPs_mm10), size = nr_subsampled_SNPs, replace = FALSE)
    SNPs_mm10_subsampled = full_SNPs_mm10[sort(SNPs_mm10_subsampled_indizes),]
    subsampled_F123_list[[seed]] = SNPs_mm10_subsampled
    print(nrow(SNPs_mm10_subsampled)/nrow(full_SNPs_mm10)*100)
    print(table(SNPs_mm10_subsampled$F123_GT)/nrow(SNPs_mm10_subsampled))
    SNPs_mm10_subsampled_chr = split(SNPs_mm10_subsampled, SNPs_mm10_subsampled$CHROM)
    mm10_SNP_subsampled_dist=unlist(lapply(SNPs_mm10_subsampled_chr,function(chr){
        dist=diff(chr$POS)
    }))
    print(mean(mm10_SNP_subsampled_dist))
    print(median(mm10_SNP_subsampled_dist))
}

# [1] 13.56867
# 
# 0|1       1|0
# 0.1286041 0.8713959
# [1] 975.02
# [1] 473
# [1] 13.56867
# 
# 0|1       1|0
# 0.1288298 0.8711702
# [1] 975.5696
# [1] 474
# [1] 13.56867
# 
# 0|1       1|0
# 0.1287478 0.8712522
# [1] 975.5532
# [1] 473
# [1] 13.56867
# 
# 0|1       1|0
# 0.1289362 0.8710638
# [1] 975.2622
# [1] 474
# [1] 13.56867
# 
# 0|1       1|0
# 0.1285281 0.8714719
# [1] 975.1567
# [1] 473
# [1] 13.56867
# 
# 0|1       1|0
# 0.1289614 0.8710386
# [1] 975.595
# [1] 474
# [1] 13.56867
# 
# 0|1       1|0
# 0.1286296 0.8713704
# [1] 975.1391
# [1] 473
# [1] 13.56867
# 
# 0|1       1|0
# 0.1288501 0.8711499
# [1] 975.4721
# [1] 474
# [1] 13.56867
# 
# 0|1       1|0
# 0.1288274 0.8711726
# [1] 975.5883
# [1] 474
# [1] 13.56867
# 
# 0|1       1|0
# 0.1291746 0.8708254
# [1] 975.6271
# [1] 474

# looks good

# save those subsampled SNPs
#/fast/groups/ag_schwarz/Projects/project-gam/Co-Phasing/prelim/subsampled_F123
saveRDS(subsampled_F123_list,'/fast/groups/ag_schwarz/Projects/project-gam/Co-Phasing/prelim/subsampled_F123/F123_mm10_GT_subsampled_to_human_SNPdensity_10times.rds')
for(i in 1:length(subsampled_F123_list)){
    print(i)
    write.csv(subsampled_F123_list[[i]],paste('/fast/groups/ag_schwarz/Projects/project-gam/Co-Phasing/prelim/subsampled_F123/F123_mm10_GT_subsampled_to_human_SNPdensity_',i,'.csv',sep=''),quote=F,row.names=F,col.names=T)
}
################################################################################
################################################################################
##### create SNP seeds of subsampled set for each file #########################
################################################################################
################################################################################
# copied from GAM/H1_Genotyping_Phasing/src/create_sample_spec_SNP_seeds_to_find_closest_obs_SNP.R
# mkdir closest_SNP_seed_files_subsampled_1
# mkdir closest_SNP_seed_files_subsampled_2
# mkdir closest_SNP_seed_files_subsampled_3
# mkdir closest_SNP_seed_files_subsampled_4
# mkdir closest_SNP_seed_files_subsampled_5
# mkdir closest_SNP_seed_files_subsampled_6
# mkdir closest_SNP_seed_files_subsampled_7
# mkdir closest_SNP_seed_files_subsampled_8
# mkdir closest_SNP_seed_files_subsampled_9
# mkdir closest_SNP_seed_files_subsampled_10

subsampled_F123_list=readRDS('/fast/groups/ag_schwarz/Projects/project-gam/Co-Phasing/prelim/subsampled_F123/F123_mm10_GT_subsampled_to_human_SNPdensity_10times.rds')

# libraries
library(GAMIBHEAR)
library(stringr)
library(data.table)

chrom_order=paste("chr",c(1:19),sep="")

# load the F123 mpileup VCFs again, to be sure the correct samples are assigned to the correct filenames
vcf_dir = '/fast/groups/ag_schwarz/Projects/project-gam/data/F123_bam_files_1123_1NP_mm10_Sept_2019_last_base_trimmed_mpileup'
files = list.files(path = vcf_dir, pattern = '*.mpileup.vcf$')
VCF_list = load_sample_VCF(files,vcf_dir)
#processed_SNVs = process_sample_VCF(VCF_list)
processed_SNVs=readRDS("/fast/groups/ag_schwarz/Projects/project-gam/Co-Phasing/prelim/subsampled_F123/processed_F123_SNPs.rds")


# merge the SNPs with the 10 subsampled F123 genomes
processed_SNVs_merged_subsampled = lapply(subsampled_F123_list,function(i){
    obs_truth_merged = merge(processed_SNVs,i,by=c("CHROM","POS"))
    obs_truth_merged = obs_truth_merged[order(as.numeric(obs_truth_merged$POS)),]
    obs_truth_merged = obs_truth_merged[order(match(obs_truth_merged$CHROM,chrom_order)),]
    return(obs_truth_merged)
})

# i=subsampled_F123_list[[1]]
# dim(i) #[1] 2462745       9
# dim(processed_SNVs) #[1] 35879529        7
# dim(obs_truth_merged) #[1] 4739948      14
# dim(obs_truth_merged[!duplicated(obs_truth_merged[c("CHROM","POS")]),]) #[1] 1592473      14
# # I think that is ok. there are SNPs being observed in multiple samples, so more rows than the unique subsampled truth, but many observations are discarded due to the subsampled truth and not all SNPs from the subsa,pled truth are observed 


SNP_seed_beds_base = lapply(processed_SNVs_merged_subsampled,function(obs_truth_merged){
    obs_truth_merged$CASTcount=0
    obs_truth_merged$J129count=0
    obs_truth_merged$CASTcount[which(obs_truth_merged$F123_GT=='1|0')]=obs_truth_merged$ALT_COUNT[which(obs_truth_merged$F123_GT=='1|0')]
    obs_truth_merged$CASTcount[which(obs_truth_merged$F123_GT=='0|1')]=obs_truth_merged$REF_COUNT[which(obs_truth_merged$F123_GT=='0|1')]
    obs_truth_merged$J129count[which(obs_truth_merged$F123_GT=='1|0')]=obs_truth_merged$REF_COUNT[which(obs_truth_merged$F123_GT=='1|0')]
    obs_truth_merged$J129count[which(obs_truth_merged$F123_GT=='0|1')]=obs_truth_merged$ALT_COUNT[which(obs_truth_merged$F123_GT=='0|1')]
    obs_truth_merged$START = obs_truth_merged$POS-1
    obs_truth_merged$PARENT = c("CAST","J129")[apply(obs_truth_merged[,c("CASTcount","J129count")],1,which.max)]
    SNP_seed_beds=obs_truth_merged[,c('CHROM','START','POS','F123_GT','PARENT','SAMPLE')]
    
    return(SNP_seed_beds)
})
saveRDS(SNP_seed_beds_base,'/fast/groups/ag_schwarz/Projects/project-gam/Co-Phasing/prelim/subsampled_F123/F123_mm10_GT_subsampled_to_human_SNPdensity_10times_Snpseeds.rds')

# now write them out, in 10 different directories
samples_sort = unique(processed_SNVs$SAMPLE)[order(as.numeric(substring(unique(processed_SNVs$SAMPLE), 7)))] # e.g. 'sample7'


#for(i in 1:length(SNP_seed_beds_base)){print(length(unique(SNP_seed_beds_base[[i]]$SAMPLE)))} # all 1123

for(i in 1:length(SNP_seed_beds_base)){
    outfilenames=sub('\\.vcf$', paste('.closest_SNP_seed_subsampled_F123_',i,'.bed',sep=''), files)
    outdir=paste('/fast/groups/ag_schwarz/Projects/project-gam/Co-Phasing/prelim/subsampled_F123/closest_SNP_seed_files_subsampled_',i,sep='')
    SNP_seed_beds_base_iter=SNP_seed_beds_base[[i]]

    for (j in 1:length(files)){
        print(paste(i,': ',j,' / ', length(files)))
        sample_seed_SNPs=SNP_seed_beds_base_iter[which(SNP_seed_beds_base_iter$SAMPLE==samples_sort[j]),]
        if(nrow(sample_seed_SNPs)>0){
            write.table(sample_seed_SNPs,paste(outdir,outfilenames[j],sep = '/'),
                        sep = '\t',
                        quote = F,
                        row.names = F,
                        col.names = F)
        }else{print("emtpy")}
    }
}


################################################################################
################################################################################
##### subsampling F123 for 2kb dist ############################################
################################################################################
################################################################################


# F123 SNPs are filtered for mininum mappability of 1, 
# load truth
full_SNPs_mm10 = readRDS('/fast/groups/ag_schwarz/Projects/project-gam/prelim/clean_mm10_gt_merged_mappability_minmap1.rds')
nrow(full_SNPs_mm10)
# 18150228

# check SNP density here again:
# split into chromosomes, calc distance
SNPs_mm10_chr = split(full_SNPs_mm10, full_SNPs_mm10$CHROM)
mm10_SNP_dist=unlist(lapply(SNPs_mm10_chr,function(chr){
    dist=diff(chr$POS)
}))
mean(mm10_SNP_dist) # 132.3968
median(mm10_SNP_dist) # 56

# check distribution of SNPs on CAST and J129 alleles:
table(full_SNPs_mm10$F123_GT)/nrow(full_SNPs_mm10)
#       0|1       1|0
# 0.1288906 0.8711094

# check again the SNP density by just seeing how many SNPs we have for how many basepairs in the genome:
# mouse genome is how long?
chromsize_mm10=read.table('/fast/groups/ag_schwarz/Projects/project-gam/RNAseq/data/Rieke_current/genome/chromsize.tsv',header = T)
sum(chromsize_mm10$size)/nrow(full_SNPs_mm10)
# 135.6867
# almost the same as the calculated distance above

# now we want to lower the SNP density to ~ 1 SNP every 1000bp (1kb), means we need x number of SNPs for the mouse genome length
nr_subsampled_SNPs_2kb = sum(chromsize_mm10$size)/2000 #[1] 1231373
nr_subsampled_SNPs_2kb/nrow(full_SNPs_mm10)*100 # 6.784337 % 

# I will sample indizes of the rows, so I can easily subset the SNP df
subsampled_F123_2kb_list = vector(mode = "list", length = 10)
for(seed in 1:10){
    set.seed(seed)
    SNPs_mm10_subsampled_indizes = sample(x = nrow(full_SNPs_mm10), size = nr_subsampled_SNPs_2kb, replace = FALSE)
    SNPs_mm10_subsampled = full_SNPs_mm10[sort(SNPs_mm10_subsampled_indizes),]
    subsampled_F123_2kb_list[[seed]] = SNPs_mm10_subsampled
    print(nrow(SNPs_mm10_subsampled)/nrow(full_SNPs_mm10)*100)
    print(table(SNPs_mm10_subsampled$F123_GT)/nrow(SNPs_mm10_subsampled))
    SNPs_mm10_subsampled_chr = split(SNPs_mm10_subsampled, SNPs_mm10_subsampled$CHROM)
    mm10_SNP_subsampled_dist=unlist(lapply(SNPs_mm10_subsampled_chr,function(chr){
        dist=diff(chr$POS)
    }))
    print(mean(mm10_SNP_subsampled_dist))
    print(median(mm10_SNP_subsampled_dist))
}

# [1] 6.784334
# 
# 0|1       1|0
# 0.1288823 0.8711177
# [1] 1949.943
# [1] 991
# [1] 6.784334
# 
# 0|1       1|0
# 0.1287604 0.8712396
# [1] 1950.618
# [1] 994
# [1] 6.784334
# 
# 0|1      1|0
# 0.128918 0.871082
# [1] 1950.955
# [1] 991
# [1] 6.784334
# 
# 0|1       1|0
# 0.1289367 0.8710633
# [1] 1950.044
# [1] 991
# [1] 6.784334
# 
# 0|1       1|0
# 0.1287986 0.8712014
# [1] 1950.088
# [1] 990
# [1] 6.784334
# 
# 0|1       1|0
# 0.1293005 0.8706995
# [1] 1950.933
# [1] 994
# [1] 6.784334
# 
# 0|1       1|0
# 0.1287564 0.8712436
# [1] 1950.061
# [1] 991
# [1] 6.784334
# 
# 0|1       1|0
# 0.1291283 0.8708717
# [1] 1950.827
# [1] 993
# [1] 6.784334
# 
# 0|1      1|0
# 0.129013 0.870987
# [1] 1950.965
# [1] 992
# [1] 6.784334
# 
# 0|1      1|0
# 0.129078 0.870922
# [1] 1951.045
# [1] 991

# save those subsampled SNPs
saveRDS(subsampled_F123_2kb_list,'/fast/groups/ag_schwarz/Projects/project-gam/Co-Phasing/prelim/subsampled_F123_2kb_SNP_dist/F123_mm10_GT_subsampled_to_2kb_SNPdist_10times.rds')
for(i in 1:length(subsampled_F123_2kb_list)){
    print(i)
    write.csv(subsampled_F123_2kb_list[[i]],paste('/fast/groups/ag_schwarz/Projects/project-gam/Co-Phasing/prelim/subsampled_F123_2kb_SNP_dist/F123_mm10_GT_subsampled_to_2kb_SNPdist_',i,'.csv',sep=''),quote=F,row.names=F,col.names=T)
}
################################################################################
################################################################################
##### create SNP seeds of subsampled set for each file #########################
################################################################################
################################################################################
# copied from GAM/H1_Genotyping_Phasing/src/create_sample_spec_SNP_seeds_to_find_closest_obs_SNP.R

# libraries
library(GAMIBHEAR)
library(stringr)
library(data.table)

chrom_order=paste("chr",c(1:19),sep="")

# load the F123 mpileup VCFs again, to be sure the correct samples are assigned to the correct filenames
vcf_dir = '/fast/groups/ag_schwarz/Projects/project-gam/data/F123_bam_files_1123_1NP_mm10_Sept_2019_last_base_trimmed_mpileup'
files = list.files(path = vcf_dir, pattern = '*.mpileup.vcf$')
VCF_list = load_sample_VCF(files,vcf_dir)
processed_SNVs = process_sample_VCF(VCF_list)
#saveRDS(processed_SNVs,"/fast/groups/ag_schwarz/Projects/project-gam/Co-Phasing/prelim/subsampled_F123/processed_F123_SNPs.rds")
#processed_SNVs=readRDS("/fast/groups/ag_schwarz/Projects/project-gam/Co-Phasing/prelim/subsampled_F123/processed_F123_SNPs.rds")

# merge the SNPs with the 10 subsampled F123 genomes
processed_SNVs_merged_subsampled = lapply(subsampled_F123_2kb_list,function(i){
    obs_truth_merged = merge(processed_SNVs,i,by=c("CHROM","POS"))
    obs_truth_merged = obs_truth_merged[order(as.numeric(obs_truth_merged$POS)),]
    obs_truth_merged = obs_truth_merged[order(match(obs_truth_merged$CHROM,chrom_order)),]
    return(obs_truth_merged)
})

# i=subsampled_F123_2kb_list[[1]]
# dim(i) #[1] 2462745       9
# dim(processed_SNVs) #[1] 35879529        7
# dim(obs_truth_merged) #[1] 4739948      14
# dim(obs_truth_merged[!duplicated(obs_truth_merged[c("CHROM","POS")]),]) #[1] 1592473      14
# # I think that is ok. there are SNPs being observed in multiple samples, so more rows than the unique subsampled truth, but many observations are discarded due to the subsampled truth and not all SNPs from the subsa,pled truth are observed 


SNP_seed_beds_base = lapply(processed_SNVs_merged_subsampled,function(obs_truth_merged){
    obs_truth_merged$CASTcount=0
    obs_truth_merged$J129count=0
    obs_truth_merged$CASTcount[which(obs_truth_merged$F123_GT=='1|0')]=obs_truth_merged$ALT_COUNT[which(obs_truth_merged$F123_GT=='1|0')]
    obs_truth_merged$CASTcount[which(obs_truth_merged$F123_GT=='0|1')]=obs_truth_merged$REF_COUNT[which(obs_truth_merged$F123_GT=='0|1')]
    obs_truth_merged$J129count[which(obs_truth_merged$F123_GT=='1|0')]=obs_truth_merged$REF_COUNT[which(obs_truth_merged$F123_GT=='1|0')]
    obs_truth_merged$J129count[which(obs_truth_merged$F123_GT=='0|1')]=obs_truth_merged$ALT_COUNT[which(obs_truth_merged$F123_GT=='0|1')]
    obs_truth_merged$START = obs_truth_merged$POS-1
    obs_truth_merged$PARENT = c("CAST","J129")[apply(obs_truth_merged[,c("CASTcount","J129count")],1,which.max)]
    SNP_seed_beds=obs_truth_merged[,c('CHROM','START','POS','F123_GT','PARENT','SAMPLE')]
    
    return(SNP_seed_beds)
})

# now write them out, in 10 different directories
samples_sort = unique(processed_SNVs$SAMPLE)[order(as.numeric(substring(unique(processed_SNVs$SAMPLE), 7)))] # e.g. 'sample7'
#for(i in 1:length(SNP_seed_beds_base)){print(length(unique(SNP_seed_beds_base[[i]]$SAMPLE)))} # all 1123

# mkdir all of those directories!
#cd /fast/groups/ag_schwarz/Projects/project-gam/Co-Phasing/prelim/subsampled_F123_2kb_SNP_dist/
# mkdir closest_SNP_seed_files_subsampled_1
# mkdir closest_SNP_seed_files_subsampled_2
# mkdir closest_SNP_seed_files_subsampled_3
# mkdir closest_SNP_seed_files_subsampled_4
# mkdir closest_SNP_seed_files_subsampled_5
# mkdir closest_SNP_seed_files_subsampled_6
# mkdir closest_SNP_seed_files_subsampled_7
# mkdir closest_SNP_seed_files_subsampled_8
# mkdir closest_SNP_seed_files_subsampled_9
# mkdir closest_SNP_seed_files_subsampled_10

for(i in 1:length(SNP_seed_beds_base)){
    outfilenames=sub('\\.vcf$', paste('.closest_SNP_seed_subsampled_F123_',i,'.bed',sep=''), files)
    outdir=paste('/fast/groups/ag_schwarz/Projects/project-gam/Co-Phasing/prelim/subsampled_F123_2kb_SNP_dist/closest_SNP_seed_files_subsampled_',i,sep='')
    SNP_seed_beds_base_iter=SNP_seed_beds_base[[i]]
    
    for (j in 1:length(files)){
        print(paste(i,': ',j,' / ', length(files)))
        sample_seed_SNPs=SNP_seed_beds_base_iter[which(SNP_seed_beds_base_iter$SAMPLE==samples_sort[j]),]
        if(nrow(sample_seed_SNPs)>0){
            write.table(sample_seed_SNPs,paste(outdir,outfilenames[j],sep = '/'),
                        sep = '\t',
                        quote = F,
                        row.names = F,
                        col.names = F)
        }else{print("emtpy")}
    }
}

################################################################################
################################################################################
##### plot number of SNPs and chr observed per subsampled set for each file ####
################################################################################
################################################################################
library(data.table)

seed_dir='/fast/groups/ag_schwarz/Projects/project-gam/Co-Phasing/prelim/subsampled_F123_2kb_SNP_dist/closest_SNP_seed_files_subsampled_1'
snpseed_files_2kb_1=files = list.files(path = seed_dir, pattern = '*.bed$')
setwd(seed_dir)
# how many chromosomes are observed per sample
snpseed_2kb_1=lapply(snpseed_files_2kb_1,fread)
chr_number_per_sample_F123_2kb = unlist(lapply(snpseed_2kb_1,function(sample){
    return(length(unique(sample$V1)))
}))

# how many SNPs are observed per sample
snp_number_per_sample_F123_2kb = unlist(lapply(snpseed_2kb_1,nrow))

# how many snps are observed per chr per sample
snpseed_2kb_1_sample_chr = lapply(snpseed_2kb_1,function(sample){
    return(split(sample,sample$V1))
})
snps_per_chr_per_sample_F123_2kb = lapply(snpseed_2kb_1_sample_chr,function(sample){
    return(unlist(lapply(sample,nrow)))
})

saveRDS(list(chr_number_per_sample_F123_2kb,snp_number_per_sample_F123_2kb,snps_per_chr_per_sample_F123_2kb),"/fast/groups/ag_schwarz/Projects/project-gam/Co-Phasing/prelim/subsampled_F123/subsampled_2kb_obs_chr_snps.rds")
#scp bih:/fast/groups/ag_schwarz/Projects/project-gam/Co-Phasing/prelim/subsampled_F123/subsampled_2kb_obs_chr_snps.rds /Users/jmarkow/Desktop/GAM/Co-Phasing/prelim/
x=readRDS("/Users/jmarkow/Desktop/GAM/Co-Phasing/prelim/subsampled_2kb_obs_chr_snps.rds")
chr_number_per_sample_F123_2kb=x[[1]]
snp_number_per_sample_F123_2kb=x[[2]]
snps_per_chr_per_sample_F123_2kb=x[[3]]

seed_dir='/fast/groups/ag_schwarz/Projects/project-gam/Co-Phasing/prelim/subsampled_F123/closest_SNP_seed_files_subsampled_1'
snpseed_files_1kb_1=files = list.files(path = seed_dir, pattern = '*.bed$')
setwd(seed_dir)
snpseed_1kb_1=lapply(snpseed_files_1kb_1,fread)
chr_number_per_sample_F123_1kb = unlist(lapply(snpseed_1kb_1,function(sample){
    return(length(unique(sample$V1)))
}))

# how many SNPs are observed per sample
snp_number_per_sample_F123_1kb = unlist(lapply(snpseed_1kb_1,nrow))

# how many snps are observed per chr per sample
snpseed_1kb_1_sample_chr = lapply(snpseed_1kb_1,function(sample){
    return(split(sample,sample$V1))
})
snps_per_chr_per_sample_F123_1kb = lapply(snpseed_1kb_1_sample_chr,function(sample){
    return(unlist(lapply(sample,nrow)))
})

saveRDS(list(chr_number_per_sample_F123_1kb,snp_number_per_sample_F123_1kb,snps_per_chr_per_sample_F123_1kb),"/fast/groups/ag_schwarz/Projects/project-gam/Co-Phasing/prelim/subsampled_F123/subsampled_1kb_obs_chr_snps.rds")
#scp bih:/fast/groups/ag_schwarz/Projects/project-gam/Co-Phasing/prelim/subsampled_F123/subsampled_1kb_obs_chr_snps.rds /Users/jmarkow/Desktop/GAM/Co-Phasing/prelim/
x=readRDS("/Users/jmarkow/Desktop/GAM/Co-Phasing/prelim/subsampled_1kb_obs_chr_snps.rds")
chr_number_per_sample_F123_1kb=x[[1]]
snp_number_per_sample_F123_1kb=x[[2]]
snps_per_chr_per_sample_F123_1kb=x[[3]]

H1_processed_SNVs_merged_truth_red=readRDS('/fast/groups/ag_schwarz/Projects/project-gam/H1/AS/prelim/H1_mpileup_truth_merged_ref_alt_phased_checked.rds')
H1_processed_SNVs_merged_truth_red = H1_processed_SNVs_merged_truth_red[order(H1_processed_SNVs_merged_truth_red$POS),]
H1_processed_SNVs_merged_truth_red = H1_processed_SNVs_merged_truth_red[order(as.numeric(substring(H1_processed_SNVs_merged_truth_red$CHROM, 4))),]
H1_processed_SNVs_merged_truth_red_sample=split(H1_processed_SNVs_merged_truth_red,H1_processed_SNVs_merged_truth_red$SAMPLE)
# split the observations by sample, see how far the distance of observed SNPs is
chr_number_per_sample_H1 = unlist(lapply(H1_processed_SNVs_merged_truth_red_sample,function(sample){
    return(length(unique(sample$CHROM)))
}))

# how many SNPs are observed per sample
snp_number_per_sample_H1 = unlist(lapply(H1_processed_SNVs_merged_truth_red_sample,nrow))

# how many snps are observed per chr per sample
snpseed_H1_sample_chr = lapply(H1_processed_SNVs_merged_truth_red_sample,function(sample){
    return(split(sample,sample$CHROM))
})
snps_per_chr_per_sample_H1 = lapply(snpseed_H1_sample_chr,function(sample){
    return(unlist(lapply(sample,nrow)))
})

saveRDS(list(chr_number_per_sample_H1,snp_number_per_sample_H1,snps_per_chr_per_sample_H1),"/fast/groups/ag_schwarz/Projects/project-gam/Co-Phasing/prelim/subsampled_F123/H1_obs_chr_snps.rds")
#scp bih:/fast/groups/ag_schwarz/Projects/project-gam/Co-Phasing/prelim/subsampled_F123/H1_obs_chr_snps.rds /Users/jmarkow/Desktop/GAM/Co-Phasing/prelim/
x=readRDS("/Users/jmarkow/Desktop/GAM/Co-Phasing/prelim/H1_obs_chr_snps.rds")
chr_number_per_sample_H1=x[[1]]
snp_number_per_sample_H1=x[[2]]
snps_per_chr_per_sample_H1=x[[3]]

# check full F123 for comparison
F123_obs=readRDS('/fast/groups/ag_schwarz/Projects/project-gam/prelim/processed_all_SNPs_F123_mm10_wo_stat_homo_minmap1.rds')


F123_obs_sample=split(F123_obs,F123_obs$SAMPLE)
# split the observations by sample, see how far the distance of observed SNPs is
chr_number_per_sample_F123 = unlist(lapply(F123_obs_sample,function(sample){
    return(length(unique(sample$CHROM)))
}))

# how many SNPs are observed per sample
snp_number_per_sample_F123 = unlist(lapply(F123_obs_sample,nrow))

# how many snps are observed per chr per sample
F123_sample_chr = lapply(F123_obs_sample,function(sample){
    return(split(sample,sample$CHROM))
})
snps_per_chr_per_sample_F123 = lapply(F123_sample_chr,function(sample){
    return(unlist(lapply(sample,nrow)))
})

saveRDS(list(chr_number_per_sample_F123,snp_number_per_sample_F123,snps_per_chr_per_sample_F123),"/fast/groups/ag_schwarz/Projects/project-gam/Co-Phasing/prelim/subsampled_F123/F123_obs_chr_snps.rds")
#scp bih:/fast/groups/ag_schwarz/Projects/project-gam/Co-Phasing/prelim/subsampled_F123/F123_obs_chr_snps.rds /Users/jmarkow/Desktop/GAM/Co-Phasing/prelim/
x=readRDS("/Users/jmarkow/Desktop/GAM/Co-Phasing/prelim/F123_obs_chr_snps.rds")
chr_number_per_sample_F123=x[[1]]
snp_number_per_sample_F123=x[[2]]
snps_per_chr_per_sample_F123=x[[3]]

### plots:  H1 vs subsampled F123 1kb SNP dist vs subsampled F123 2kb SNP dist
### number of chr observed in each sample:

chr_list=list(chr_number_per_sample_H1,chr_number_per_sample_F123,chr_number_per_sample_F123_1kb,chr_number_per_sample_F123_2kb)
boxplot(chr_list,xaxt="none")
axis(1,at=1:4,labels = c("H1","F123 full","F123 sub 1kb","F123 sub 2kb"))
par(mfrow=c(4,1))
hist(chr_list[[1]],main="H1",xlab="chr",breaks=seq(-0.5,22.5,1))
hist(chr_list[[2]],main="F123",xlab="chr",breaks=seq(-0.5,19.5,1))
hist(chr_list[[3]],main="F123 sub 1kb",xlab="chr",breaks=seq(-0.5,19.5,1))
hist(chr_list[[4]],main="F123 sub 2kb",xlab="chr",breaks=seq(-0.5,19.5,1))

### number of snps observed in each sample:

snp_list=list(snp_number_per_sample_H1,snp_number_per_sample_F123,snp_number_per_sample_F123_1kb,snp_number_per_sample_F123_2kb)
par(mfrow=c(1,1))
boxplot(snp_list,xaxt="none",outline=F)
axis(1,at=1:4,labels = c("H1","F123 full","F123 sub 1kb","F123 sub 2kb"))
# par(mfrow=c(4,1))
# hist(snp_list[[1]],main="H1",xlab="number of SNPs")
# hist(snp_list[[2]],main="F123",xlab="number of SNPs")
# hist(snp_list[[3]],main="F123 sub 1kb",xlab="number of SNPs")
# hist(snp_list[[4]],main="F123 sub 2kb",xlab="number of SNPs")


### number of snps observed in chr in each sample:
snps_per_chr_per_sample_F123_df = do.call(rbind, lapply(snps_per_chr_per_sample_F123, function(x) x[match(paste("chr",1:19,sep=""), names(x))]))
colnames(snps_per_chr_per_sample_F123_df)=paste("chr",1:19,sep="")
snps_per_chr_per_sample_F123_1kb_df = do.call(rbind, lapply(snps_per_chr_per_sample_F123_1kb, function(x) x[match(paste("chr",1:19,sep=""), names(x))]))
colnames(snps_per_chr_per_sample_F123_1kb_df)=paste("chr",1:19,sep="")
snps_per_chr_per_sample_F123_2kb_df = do.call(rbind, lapply(snps_per_chr_per_sample_F123_2kb, function(x) x[match(paste("chr",1:19,sep=""), names(x))]))
colnames(snps_per_chr_per_sample_F123_2kb_df)=paste("chr",1:19,sep="")
snps_per_chr_per_sample_H1_df = do.call(rbind, lapply(snps_per_chr_per_sample_H1, function(x) x[match(paste("chr",1:22,sep=""), names(x))]))
colnames(snps_per_chr_per_sample_H1_df)=paste("chr",1:22,sep="")

snps_per_chr_per_sample_F123_df[which(is.na(snps_per_chr_per_sample_F123_df))]=0
snps_per_chr_per_sample_F123_1kb_df[which(is.na(snps_per_chr_per_sample_F123_1kb_df))]=0
snps_per_chr_per_sample_F123_2kb_df[which(is.na(snps_per_chr_per_sample_F123_2kb_df))]=0
snps_per_chr_per_sample_H1_df[which(is.na(snps_per_chr_per_sample_H1_df))]=0

# now, how to plot this?
par(mfrow=c(4,1))
hist(snps_per_chr_per_sample_H1_df,breaks=c(-0.5,seq(0.5,(max(snps_per_chr_per_sample_H1_df)+10.5),10)),xlab="number of SNPs",main="number of SNPs observed per chromosome per sample in H1")
hist(snps_per_chr_per_sample_F123_df,breaks=c(-0.5,seq(0.5,(max(snps_per_chr_per_sample_F123_df)+10.5),10)),xlab="number of SNPs",main="number of SNPs observed per chromosome per sample in F123")
hist(snps_per_chr_per_sample_F123_1kb_df,breaks=c(-0.5,seq(0.5,(max(snps_per_chr_per_sample_F123_1kb_df)+10.5),10)),xlab="number of SNPs",main="number of SNPs observed per chromosome per sample in F123 sub 1kb")
hist(snps_per_chr_per_sample_F123_2kb_df,breaks=c(-0.5,seq(0.5,(max(snps_per_chr_per_sample_F123_2kb_df)+10.5),10)),xlab="number of SNPs",main="number of SNPs observed per chromosome per sample in F123 sub 2kb")

hist(snps_per_chr_per_sample_H1_df,breaks=c(-0.5,seq(0.5,(max(snps_per_chr_per_sample_H1_df)+1.5),1)),xlim=c(0,500),xlab="number of SNPs",main="number of SNPs observed per chromosome per sample in H1")
hist(snps_per_chr_per_sample_F123_df,breaks=c(-0.5,seq(0.5,(max(snps_per_chr_per_sample_F123_df)+1.5),1)),xlim=c(0,500),xlab="number of SNPs",main="number of SNPs observed per chromosome per sample in F123")
hist(snps_per_chr_per_sample_F123_1kb_df,breaks=c(-0.5,seq(0.5,(max(snps_per_chr_per_sample_F123_1kb_df)+1.5),1)),xlim=c(0,500),xlab="number of SNPs",main="number of SNPs observed per chromosome per sample in F123 sub 1kb")
hist(snps_per_chr_per_sample_F123_2kb_df,breaks=c(-0.5,seq(0.5,(max(snps_per_chr_per_sample_F123_2kb_df)+1.5),1)),xlim=c(0,500),xlab="number of SNPs",main="number of SNPs observed per chromosome per sample in F123 sub 2kb")

hist(snps_per_chr_per_sample_H1_df,breaks=c(-0.5,seq(0.5,(max(snps_per_chr_per_sample_H1_df)+1.5),1)),xlim=c(0,100),xlab="number of SNPs",main="number of SNPs observed per chromosome per sample in H1")
hist(snps_per_chr_per_sample_F123_df,breaks=c(-0.5,seq(0.5,(max(snps_per_chr_per_sample_F123_df)+1.5),1)),xlim=c(0,100),xlab="number of SNPs",main="number of SNPs observed per chromosome per sample in F123")
hist(snps_per_chr_per_sample_F123_1kb_df,breaks=c(-0.5,seq(0.5,(max(snps_per_chr_per_sample_F123_1kb_df)+1.5),1)),xlim=c(0,100),xlab="number of SNPs",main="number of SNPs observed per chromosome per sample in F123 sub 1kb")
hist(snps_per_chr_per_sample_F123_2kb_df,breaks=c(-0.5,seq(0.5,(max(snps_per_chr_per_sample_F123_2kb_df)+1.5),1)),xlim=c(0,100),xlab="number of SNPs",main="number of SNPs observed per chromosome per sample in F123 sub 2kb")




################################################################################
################################################################################
##### create SNP seeds of subsampled set for each file 3NPs ####################
################################################################################
################################################################################
mkdir /fast/groups/ag_schwarz/Projects/project-gam/Co-Phasing/prelim/subsampled_F123_3NPs_1kb_SNP_dist
cd /fast/groups/ag_schwarz/Projects/project-gam/Co-Phasing/prelim/subsampled_F123_3NPs_1kb_SNP_dist
# mkdir closest_SNP_seed_files_subsampled_1
# mkdir closest_SNP_seed_files_subsampled_2
# mkdir closest_SNP_seed_files_subsampled_3
# mkdir closest_SNP_seed_files_subsampled_4
# mkdir closest_SNP_seed_files_subsampled_5
# mkdir closest_SNP_seed_files_subsampled_6
# mkdir closest_SNP_seed_files_subsampled_7
# mkdir closest_SNP_seed_files_subsampled_8
# mkdir closest_SNP_seed_files_subsampled_9
# mkdir closest_SNP_seed_files_subsampled_10

subsampled_F123_list=readRDS('/fast/groups/ag_schwarz/Projects/project-gam/Co-Phasing/prelim/subsampled_F123/F123_mm10_GT_subsampled_to_human_SNPdensity_10times.rds')

# libraries
library(GAMIBHEAR)
library(stringr)
library(data.table)

chrom_order=paste("chr",c(1:19),sep="")

# load the F123 mpileup VCFs again, to be sure the correct samples are assigned to the correct filenames
vcf_dir = '/fast/groups/ag_schwarz/Projects/project-gam/results/F123_3NP_mpileup_AD_ref'
files = list.files(path = vcf_dir, pattern = '*.mpileup.vcf$') # those are not autosomes, but the merging with the truth should take care of that
VCF_list = load_sample_VCF(files,vcf_dir)
processed_SNVs = process_sample_VCF(VCF_list)
# waiting for this 
saveRDS(list(files,processed_SNVs),'/fast/groups/ag_schwarz/Projects/project-gam/Co-Phasing/prelim/subsampled_F123/F123_3NP_mm10_all_files_and_processed_observed_SNPs.rds')

# merge the SNPs with the 10 subsampled F123 genomes
processed_SNVs_merged_subsampled = lapply(subsampled_F123_list,function(i){
    obs_truth_merged = merge(processed_SNVs,i,by=c("CHROM","POS"))
    obs_truth_merged = obs_truth_merged[order(as.numeric(obs_truth_merged$POS)),]
    obs_truth_merged = obs_truth_merged[order(match(obs_truth_merged$CHROM,chrom_order)),]
    return(obs_truth_merged)
})

# i=subsampled_F123_list[[1]]
# dim(i) #[1] 2462745       9
# dim(processed_SNVs) #[1] 35879529        7
# dim(obs_truth_merged) #[1] 4739948      14
# dim(obs_truth_merged[!duplicated(obs_truth_merged[c("CHROM","POS")]),]) #[1] 1592473      14
# # I think that is ok. there are SNPs being observed in multiple samples, so more rows than the unique subsampled truth, but many observations are discarded due to the subsampled truth and not all SNPs from the subsa,pled truth are observed 


SNP_seed_beds_base = lapply(processed_SNVs_merged_subsampled,function(obs_truth_merged){
    obs_truth_merged$CASTcount=0
    obs_truth_merged$J129count=0
    obs_truth_merged$CASTcount[which(obs_truth_merged$F123_GT=='1|0')]=obs_truth_merged$ALT_COUNT[which(obs_truth_merged$F123_GT=='1|0')]
    obs_truth_merged$CASTcount[which(obs_truth_merged$F123_GT=='0|1')]=obs_truth_merged$REF_COUNT[which(obs_truth_merged$F123_GT=='0|1')]
    obs_truth_merged$J129count[which(obs_truth_merged$F123_GT=='1|0')]=obs_truth_merged$REF_COUNT[which(obs_truth_merged$F123_GT=='1|0')]
    obs_truth_merged$J129count[which(obs_truth_merged$F123_GT=='0|1')]=obs_truth_merged$ALT_COUNT[which(obs_truth_merged$F123_GT=='0|1')]
    obs_truth_merged$START = obs_truth_merged$POS-1
    obs_truth_merged$PARENT = c("CAST","J129")[apply(obs_truth_merged[,c("CASTcount","J129count")],1,which.max)]
    SNP_seed_beds=obs_truth_merged[,c('CHROM','START','POS','F123_GT','PARENT','SAMPLE')]
    
    return(SNP_seed_beds)
})
saveRDS(SNP_seed_beds_base,'/fast/groups/ag_schwarz/Projects/project-gam/Co-Phasing/prelim/subsampled_F123/F123_3NPs_mm10_GT_subsampled_to_human_SNPdensity_10times_Snpseeds.rds')

# now write them out, in 10 different directories
samples_sort = unique(processed_SNVs$SAMPLE)[order(as.numeric(substring(unique(processed_SNVs$SAMPLE), 7)))] # e.g. 'sample7'


#for(i in 1:length(SNP_seed_beds_base)){print(length(unique(SNP_seed_beds_base[[i]]$SAMPLE)))} # all 1123

for(i in 1:length(SNP_seed_beds_base)){
    outfilenames=sub('\\.vcf$', paste('.closest_SNP_seed_subsampled_F123_3NP_',i,'.bed',sep=''), files)
    outdir=paste('/fast/groups/ag_schwarz/Projects/project-gam/Co-Phasing/prelim/subsampled_F123_3NPs_1kb_SNP_dist/closest_SNP_seed_files_subsampled_',i,sep='')
    SNP_seed_beds_base_iter=SNP_seed_beds_base[[i]]
    
    for (j in 1:length(files)){
        print(paste(i,': ',j,' / ', length(files)))
        sample_seed_SNPs=SNP_seed_beds_base_iter[which(SNP_seed_beds_base_iter$SAMPLE==samples_sort[j]),]
        if(nrow(sample_seed_SNPs)>0){
            write.table(sample_seed_SNPs,paste(outdir,outfilenames[j],sep = '/'),
                        sep = '\t',
                        quote = F,
                        row.names = F,
                        col.names = F)
        }else{print("emtpy")}
    }
}


################################################################################
################################################################################
##### plots for student seminar F123 1kb subsampled ############################
################################################################################
################################################################################
# 24.05.21
# Sasha gave me a table with phasing efficiency
library(data.table)
phase_eff=fread("/Users/jmarkow/Desktop/GAM/Co-Phasing/prelim/F123.subsampling.phasing.efficiencies.SNP1Kb.table")
dim(phase_eff)
head(phase_eff)
phase_eff$dist=substring(phase_eff$Distance_cutoff,13)
phase_eff$res=substring(phase_eff$Resolution,5)

unique(phase_eff$dist)
phase_eff = phase_eff[order(as.numeric(phase_eff$res)),]
phase_eff = phase_eff[order(as.numeric(phase_eff$dist)),]

# I need stacked bar plots
phase_eff$Iteration = factor(phase_eff$Iteration,levels=paste("iteration_",1:10,sep=""))
#phase_eff_iter=split(phase_eff,phase_eff$Iteration)
phase_eff_split_d = split(phase_eff,phase_eff$dist)
phase_eff_split_dr = lapply(phase_eff_split_d,function(dist){
    return(split(dist,dist$res))
})
phase_eff_split_dr_flat = unlist(phase_eff_split_dr,recursive=FALSE)
phase_eff_mean = lapply(phase_eff_split_dr_flat,function(const){
    CAST_eff = mean(const$CAST_efficiency)
    J129_eff = mean(const$S129_efficiency)
    Dual_eff = mean(const$Dual_efficiency)
    dist = const$dist[1]
    res = as.numeric(const$res[1])
    return(data.frame(dist,res,CAST_eff,J129_eff,Dual_eff,stringsAsFactors=FALSE))
})
phase_eff_mean = do.call(rbind,phase_eff_mean)

# phase_eff_mean_dsplit = split(phase_eff_mean,phase_eff_mean$dist)
# phase_eff_mean_dsplit_plot = lapply(phase_eff_mean_dsplit,function(d){
#     return_table = as.data.frame(t(d[,3:5]))
#     colnames(return_table) = d$res
#     return_table = return_table[,order(as.numeric(d$res))]
#     return_table = as.matrix(return_table)
#     colnames(return_table) = c("50 kb","100 kb","200 kb")
#     return(return_table[nrow(return_table):1,])
# })
# names(phase_eff_mean_dsplit_plot) = c("0 bp", "100 kb", "200 kb", "50 kb", "no cut-off")
# phase_eff_mean_dsplit_plot = phase_eff_mean_dsplit_plot[c("0 bp", "50 kb","100 kb", "200 kb", "no cut-off")]
# 
# # Get the stacked barplot
# pdf("/Users/jmarkow/Desktop/GAM/Co-Phasing/WPE_subF123_1NP_1kb.pdf",width=6,height=6)
# for (i in 1:length(phase_eff_mean_dsplit_plot)){
#     counts = phase_eff_mean_dsplit_plot[[i]]
#     bp=barplot(counts, main="Window Phasing Efficiency", 
#                ylab="Percent of positive windows",ylim=c(0,100),#yaxt="none",
#                xlab="Resolution", col=c("grey",rgb(79,173,234,maxColorValue = 255),rgb(237,125,49,maxColorValue = 255)),
#                legend = c("Both","Genome 2", "Genome 1"))
#     text(bp,counts[1,]/2,labels=round(counts[1,],2),cex=0.8)
#     text(bp,(counts[1,]+(counts[2,]/2)),labels=round(counts[2,],2),cex=0.8)
#     text(bp,(counts[1,]+counts[2,]+(counts[3,]/2)),labels=round(counts[3,],2),cex=0.8)
# }
# dev.off()


phase_eff_mean_rsplit = split(phase_eff_mean,phase_eff_mean$res)
phase_eff_mean_rsplit_plot = lapply(phase_eff_mean_rsplit,function(d){
    return_table = as.data.frame(t(d[,c("CAST_eff","J129_eff","Dual_eff")]))
    colnames(return_table) = d$dist
    return_table = as.matrix(return_table)
    colnames(return_table) = c("0 bp", "100 kb", "200 kb", "50 kb", "no cut-off")
    return_table = return_table[,c("0 bp", "50 kb","100 kb", "200 kb", "no cut-off")]
    return(return_table[nrow(return_table):1,])
})
names(phase_eff_mean_rsplit_plot) = c("50 kb","100 kb", "200 kb")

# Get the stacked barplot
for (i in 1:length(phase_eff_mean_rsplit_plot)){
pdf(paste("/Users/jmarkow/Desktop/GAM/Co-Phasing/WPE_subF123_1NP_1kb_",names(phase_eff_mean_rsplit_plot)[i],"_res.pdf",sep=""),width=6,height=6)

    counts = phase_eff_mean_rsplit_plot[[i]]
    bp=barplot(counts, main=paste("Window Phasing Efficiency\n",names(phase_eff_mean_rsplit_plot)[i], " resolution",sep=""),
               ylab="Percent of positive windows",ylim=c(0,100),#yaxt="none",
               xlab="Distance threshold", col=c("grey",rgb(79,173,234,maxColorValue = 255),rgb(237,125,49,maxColorValue = 255)),
               legend = c("Both","Genome 2", "Genome 1"))
    text(bp,counts[1,]/2,labels=round(counts[1,],2),cex=0.8)
    text(bp,(counts[1,]+(counts[2,]/2)),labels=round(counts[2,],2),cex=0.8)
    text(bp,(counts[1,]+counts[2,]+(counts[3,]/2)),labels=round(counts[3,],2),cex=0.8)

 dev.off()
}



# redo the H1 plot to complement the subsampled F123 window efficiency plor 
counts = cbind(c(8.71,8.43,0.61),
               c(11.92,11.53,1.05),
               c(18.22,17.64,1.58),
               c(23.69,22.97,1.71),
               c(30.11,29.22,1.8),
               c(49.61,48.47,1.89))
counts = counts[nrow(counts):1,]
colnames(counts) = c("0 bp","1 kb", "50 kb","100 kb", "200 kb", "no cut-off")

pdf("/Users/jmarkow/Desktop/GAM/Co-Phasing/WPE_cutoff_all.pdf",width=6,height=6)
bp=barplot(counts, main="Window Phasing Efficiency", 
        ylab="Percent of positive windows",ylim=c(0,100),#yaxt="none",
        xlab="Distance threshold", col=c("grey",rgb(79,173,234,maxColorValue = 255),rgb(237,125,49,maxColorValue = 255)),
        legend = c("Both","Genome 2", "Genome 1"))
#axis(2,at=c(seq(0,10000,2000)),labels = seq(0,100,20))
text(bp,counts[1,]/2,labels=round(counts[1,],2),cex=0.8)
text(bp,(counts[1,]+(counts[2,]/2)),labels=round(counts[2,],2),cex=0.8)
text(bp,(counts[1,]+counts[2,]+(counts[3,]/2)),labels=round(counts[3,],2),cex=0.8)
dev.off()


